// src/lib/components/sections/Footer.svelte
<script>
	import Icon from '@iconify/svelte';
	import DotPattern from '$lib/components/shared/misc/DotPattern.svelte';
</script>

<footer class="relative bg-black">
	<div class="container pt-8 pb-4 text-white space-y-6">
		<div class="flex flex-col sm:flex-row gap-8 justify-center">
			<div class="text-right space-y-2">
				<p class="text-4xl">Code</p>
				<p class="text-4xl">mit</p>
				<p class="text-4xl">Leidenschaft.</p>
			</div>

			<div
				class="flex flex-row sm:flex-col flex-wrap justify-center sm:items-start gap-x-10 sm:gap-x-0 gap-y-4"
			>
				<a
					class="flex flex-row gap-2 justify-start sm:justify-center group items-center"
					href="mailto:michael.philipp.holley@gmail.com"
					aria-label="GitHub-Profile"
				>
					<div class="group-hover:scale-110 transition-all">
						<Icon icon="tdesign:mail-filled" style="font-size:2rem" />
					</div>
					Contact me
				</a>
				<a
					class="flex flex-row gap-2 justify-start sm:justify-center group items-center"
					href="https://github.com/MichaelHolley"
					target="_blank"
					rel="noreferrer"
					aria-label="GitHub-Profile"
				>
					<div class="group-hover:scale-110 transition-all">
						<Icon icon="fa:github" style="font-size:2rem" />
					</div>
					GitHub
				</a>
				<a
					class="flex flex-row gap-2 justify-start sm:justify-center group items-center"
					href="https://www.linkedin.com/in/michael-holley-791a64228/"
					target="_blank"
					rel="noreferrer"
					aria-label="LinkedIn-Profile"
				>
					<div class="group-hover:scale-110 transition-all">
						<Icon icon="fa:linkedin-square" style="font-size:2rem" />
					</div>
					LinkedIn
				</a>
			</div>
		</div>
		<p class="text-center text-sm">&copy; {new Date().getFullYear()} Michael Holley</p>
	</div>

	<DotPattern
		width={20}
		height={20}
		cx={10}
		cy={10}
		cr={1}
		class="[mask-image:linear-gradient(to_bottom_left,white,transparent,transparent)] "
	/>
</footer>

// src/components/footer.tsx
import React from 'react';
import { FaXing } from 'react-icons/fa';
import { FiLinkedin, FiGithub, FiMail } from 'react-icons/fi';

function Footer() {
  return (
    <footer className='bg-b0 bg-opacity-60 shadow-2xl fixed z-20 bottom-5 right-5 p-3 rounded-full border-2 border-w0 backdrop-blur-[2px]'>
      <ul className='flex flex-row-reverse text-w0'>
        <NavBarIconItem
          icon={
            <FaXing
              size='1.5em'
              className='transition ease-out duration-300 hover:scale-110'
            />
          }
          link='https://www.xing.com/profile/Michael_Holley'
          title='Xing'></NavBarIconItem>
        <NavBarIconItem
          icon={
            <FiLinkedin
              size='1.5em'
              className='transition ease-out duration-300 hover:scale-110'
            />
          }
          link='https://www.linkedin.com/in/michael-holley-791a64228/'
          title='LinkedIn'></NavBarIconItem>
        <NavBarIconItem
          icon={
            <FiMail
              size='1.5em'
              className='transition ease-out duration-300 hover:scale-110'
            />
          }
          link='mailto:michael.philipp.holley@gmail.com'
          title='Mail'></NavBarIconItem>
        <NavBarIconItem
          icon={
            <FiGithub
              size='1.5em'
              className='transition ease-out duration-300 hover:scale-110'
            />
          }
          link='https://github.com/MichaelHolley'
          title='GitHub'></NavBarIconItem>
      </ul>
    </footer>
  );
}

function NavBarIconItem(props: {
  icon: JSX.Element;
  link: string;
  title: string;
}) {
  return (
    <li className='mx-[6px] group'>
      <a href={props.link} target='_blank' rel='noreferrer'>
        {props.icon}
      </a>
      <span className='absolute w-auto px-1 m-2 -top-[3.7rem] -ml-2 rounded-md shadow-2xl text-w0 bg-b0 bg-opacity-60 origin-left opacity-0 group-hover:-top-10 transition-all group-hover:opacity-100 duration-[400ms] ease-in-out'>
        {props.title}
      </span>
    </li>
  );
}

export default Footer;
